import { Skill } from "@models/project.interface";

export const SKILLS: Skill[] = [
  {name: 'HTML', icon: 'html'},
  {name: 'CSS', icon: 'css'},
  {name: 'SCSS', icon: 'scss'},
  {name: 'Tailwind CSS', icon: 'tailwind'},
  {name: 'JavaScript', icon: 'javascript'},
  {name: 'TypeScript', icon: 'typescript'},
  {name: 'Angular', icon: 'angular'},
  {name: 'Vue.js', icon: 'vue'},
  {name: 'React', icon: 'react'},
  {name: 'NodeJS', icon: 'nodejs'},
  {name: 'Express.js', icon: 'express'},
  {name: 'NestJS', icon: 'nestjs'},
  {name: 'Loopback', icon: 'loopback'},
  {name: 'Jest', icon: 'jest'},
  {name: 'MySQL', icon: 'mysql'},
  {name: 'PostgreSQL', icon: 'postgresql'},
  {name: 'Oracle PL/SQL', icon: 'oracle'},
  {name: 'RabbitMQ', icon: 'rabbitmq'},
  {name: 'Docker', icon: 'docker'},
  {name: 'Kubernetes', icon: 'kubernetes'},
  {name: 'Helm', icon: 'helm'},
  {name: 'Terraform', icon: 'terraform'},
  {name: 'Azure', icon: 'azure'},
  {name: 'GCP', icon: 'gcp'},
  {name: 'Linux', icon: 'linux'},
  {name: 'Apache', icon: 'apache'},
  {name: 'PHP', icon: 'php'},
  {name: 'Laravel', icon: 'laravel'},
  {name: 'Wordpress', icon: 'wordpress'},
  {name: 'Git', icon: 'git'},
  {name: 'Gitlab', icon: 'gitlab'},
  {name: 'Teamcity', icon: 'tc'},
  {name: 'Jenkins', icon: 'jenkins'},
  {name: 'Solr', icon: 'solr'},
  {name: 'Elasticsearch', icon: 'elasticsearch'},
  {name: 'Professional Scrum Master', icon: 'psm'},
]
